# Generated by Django 2.0 on 2018-04-28 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_id', models.IntegerField(unique=True)),
                ('movie_genre', models.CharField(max_length=100, null=True)),
                ('movie_poster', models.CharField(max_length=300)),
                ('movie_date', models.DateField(verbose_name='date released')),
                ('movie_runtime', models.IntegerField()),
                ('movie_stars', models.IntegerField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime_id', models.IntegerField(max_length=200)),
                ('showtime_time', models.CharField(max_length=10)),
                ('showtime_tickets', models.CharField(max_length=250)),
                ('votes', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vis.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatre_id', models.IntegerField(unique=True)),
                ('address1', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('geo_long', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('geo_lat', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('theatre_name', models.CharField(max_length=100)),
                ('theatre_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='showtime',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vis.Theatre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='theatres',
            field=models.ManyToManyField(to='vis.Theatre'),
        ),
    ]
